fragment AccountParts on Account {
  __typename
  title
  body
}

fragment Coway_connect_applicationParts on Coway_connect_application {
  __typename
  title
  body
}

fragment Coway_mallParts on Coway_mall {
  __typename
  title
  body
}

fragment PaymentParts on Payment {
  __typename
  title
  body
}

fragment PrivacyParts on Privacy {
  __typename
  title
  body
}

fragment ProductParts on Product {
  __typename
  title
  body
}

fragment ReturnParts on Return {
  __typename
  title
  body
}

fragment ServiceParts on Service {
  __typename
  title
  body
}

fragment ShippingParts on Shipping {
  __typename
  title
  body
}
