backend:
  name: github
  repo: kritchai-dt/coway-docs
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

publish_mode: editorial_workflow
local_backend: true

collections:
  - name: "payment"
    label: "การชำระเงิน"
    folder: "docs/payment"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - label: "หัวข้อ"
        name: "title"
        widget: "string"
      - label: "ลำดับใน Sidebar"
        name: "sidebar_position"
        widget: "number"
        required: false
      - label: "เนื้อหา"
        name: "body"
        widget: "markdown"

  - name: "service"
    label: "บริการงานช่าง"
    folder: "docs/service"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - label: "หัวข้อ"
        name: "title"
        widget: "string"
      - label: "ลำดับใน Sidebar"
        name: "sidebar_position"
        widget: "number"
        required: false
      - label: "เนื้อหา"
        name: "body"
        widget: "markdown"